const UI_TEXT_MAP: Record<string, string> = {
  Cancel: 'Hủy',
  Save: 'Lưu',
  Delete: 'Xóa',
  Edit: 'Chỉnh sửa',
  Create: 'Tạo',
  Search: 'Tìm kiếm',
  Back: 'Quay lại',
  Next: 'Tiếp tục',
  Previous: 'Trước',
  Submit: 'Nộp',
  Finish: 'Hoàn tất',
  'Saving...': 'Đang lưu...',
  'Sign In': 'Đăng nhập',
  'Sign Up': 'Đăng ký',
  'Go Back': 'Quay lại',
  'Go Home': 'Về trang chủ',
  Verify: 'Xác minh',
  'Verify Code': 'Xác minh mã',
  'Send Code': 'Gửi mã',
  Username: 'Tên đăng nhập',
  Password: 'Mật khẩu',
  'New Password': 'Mật khẩu mới',
  'Current Password': 'Mật khẩu hiện tại',
  'Reset Password': 'Đặt lại mật khẩu',
  'Change Password': 'Đổi mật khẩu',
  Change: 'Đổi',
  Email: 'Email',
  'Full Name': 'Họ và tên',
  'Birthday (YYYY-MM-DD)': 'Ngày sinh (YYYY-MM-DD)',
  'Confirm Password': 'Xác nhận mật khẩu',
  'Enter OTP': 'Nhập OTP',
  'Please enter your email': 'Vui lòng nhập email',
  'Please enter new password': 'Vui lòng nhập mật khẩu mới',
  'Please confirm new password': 'Vui lòng xác nhận mật khẩu mới',
  'Password reset successfully!': 'Đặt lại mật khẩu thành công!',
  'Continue with Google': 'Tiếp tục với Google',
  'Choose Plan': 'Chọn gói',
  'Back to Plans': 'Quay lại gói',
  'Back to Workspace': 'Về workspace',
  'Back to Group': 'Về nhóm',
  'Back to Roadmap': 'Về lộ trình',
  'Back to Quizzes': 'Về danh sách quiz',
  Recommended: 'Đề xuất',
  Free: 'Miễn phí',
  Individual: 'Cá nhân',
  Group: 'Nhóm',
  Sources: 'Tài liệu',
  Quizzes: 'Bài kiểm tra',
  Cards: 'Thẻ',
  Members: 'Thành viên',
  Contributors: 'Cộng tác viên',
  Leaders: 'Trưởng nhóm',
  'Can Upload': 'Có thể tải lên',
  You: 'Bạn',
  Chat: 'Trò chuyện',
  Studio: 'Studio',
  Roadmap: 'Lộ trình',
  'Mock Test': 'Thi thử',
  Add: 'Thêm',
  Live: 'Trực tiếp',
  'Open Setup': 'Mở thiết lập',
  'Edit Profile': 'Chỉnh sửa hồ sơ',
  'Log Out': 'Đăng xuất',
  Name: 'Tên',
  Title: 'Tiêu đề',
  Description: 'Mô tả',
  'Edit Workspace': 'Sửa workspace',
  'Delete Workspace': 'Xóa workspace',
  'Group Name': 'Tên nhóm',
  'Danger Zone': 'Vùng nguy hiểm',
  'Delete Group': 'Xóa nhóm',
  'Create AI Quiz': 'Tạo bài quiz AI',
  'Create AI Flashcards': 'Tạo flashcard AI',
  'Quiz title': 'Tiêu đề quiz',
  'Question count': 'Số lượng câu hỏi',
  'Question count must be at least 1': 'Số lượng câu hỏi phải lớn hơn hoặc bằng 1',
  'Prompt (optional)': 'Prompt (tùy chọn)',
  'General Config': 'Cấu hình chung',
  'Output Language': 'Ngôn ngữ đầu ra',
  Timing: 'Thời gian',
  Timed: 'Tính giờ',
  'Per Question': 'Theo từng câu',
  'Total duration (minutes)': 'Tổng thời lượng (phút)',
  'Easy (s)': 'Dễ (giây)',
  'Medium (s)': 'Trung bình (giây)',
  'Hard (s)': 'Khó (giây)',
  'Difficulty Profile': 'Cấu hình độ khó',
  Preset: 'Mẫu cài đặt',
  'Difficulty by count': 'Độ khó theo số lượng',
  'Easy (%)': 'Dễ (%)',
  'Medium (%)': 'Trung bình (%)',
  'Hard (%)': 'Khó (%)',
  'Question Types': 'Loại câu hỏi',
  'Use count unit': 'Dùng đơn vị số lượng',
  'Bloom Skills': 'Kỹ năng Bloom',
  Materials: 'Tài liệu',
  Quantity: 'Số lượng',
  Material: 'Tài liệu',
  'Roadmap Journey': 'Hành trình lộ trình',
  Roadmaps: 'Lộ trình',
  Phases: 'Giai đoạn',
  'Generate Phases': 'Tạo giai đoạn',
  'No phase data available.': 'Chưa có dữ liệu giai đoạn.',
  'Pre-learning': 'Trước học',
  'Phase Content': 'Nội dung giai đoạn',
  'Pre-learning quiz': 'Quiz trước học',
  'Post-learning quiz': 'Quiz sau học',
  'Running action...': 'Đang chạy tác vụ...',
  Quiz: 'Quiz',
  Flashcard: 'Flashcard',
  'Invite Member': 'Mời thành viên',
  Invite: 'Mời',
  'Material Detail': 'Chi tiết tài liệu',
  Summary: 'Tóm tắt',
  'Extracted Text': 'Nội dung trích xuất',

  'Please fill in all fields': 'Vui lòng điền đầy đủ các trường',
  'Login successful!': 'Đăng nhập thành công!',
  'Google Play Services not available': 'Google Play Services không khả dụng',
  'Full name is required': 'Vui lòng nhập họ và tên',
  'Please enter a valid email address': 'Vui lòng nhập email hợp lệ',
  'Please confirm your password': 'Vui lòng xác nhận mật khẩu',
  'Passwords do not match': 'Mật khẩu xác nhận không khớp',
  'Username is already in use': 'Tên đăng nhập đã được sử dụng',
  'Email is already in use': 'Email đã được sử dụng',
  'OTP sent to your email': 'Đã gửi OTP đến email của bạn',
  'OTP resent to your email': 'Đã gửi lại OTP đến email của bạn',
  'Please enter OTP': 'Vui lòng nhập OTP',
  'Account created successfully!': 'Tạo tài khoản thành công!',
  'Failed to load workspaces/groups': 'Không thể tải danh sách workspace/nhóm',
  'Failed to create': 'Không thể tạo mới',
  'Failed to load group details': 'Không thể tải chi tiết nhóm',
  'Failed to load group data': 'Không thể tải dữ liệu nhóm',
  'Invitation sent!': 'Đã gửi lời mời!',
  'Failed to send invitation': 'Không thể gửi lời mời',
  'File upload coming soon': 'Tính năng tải file sẽ sớm ra mắt',
  'Upload granted': 'Đã cấp quyền tải lên',
  'Upload revoked': 'Đã thu hồi quyền tải lên',
  'Member promoted!': 'Đã thăng quyền thành viên!',
  'Member demoted': 'Đã hạ quyền thành viên',
  'Member removed': 'Đã xóa thành viên',
  'Failed to remove member': 'Không thể xóa thành viên',
  'Action failed': 'Thao tác thất bại',
  'Group name is required': 'Vui lòng nhập tên nhóm',
  'Workspace updated!': 'Đã cập nhật workspace!',
  'Failed to update workspace': 'Không thể cập nhật workspace',
  'Workspace deleted!': 'Đã xóa workspace!',
  'Failed to delete workspace': 'Không thể xóa workspace',
  'Quiz ID is missing': 'Thiếu Quiz ID',
  'Exam attempt is missing': 'Thiếu lượt làm bài thi',
  'Quiz activated. Starting now...': 'Quiz đã được kích hoạt. Bắt đầu ngay...',
  'Start Exam': 'Bắt đầu thi',
  'Submit Exam': 'Nộp bài thi',
  'Failed to load workspace data': 'Không thể tải dữ liệu workspace',
  'Workspace Profile Setup Required': 'Cần thiết lập hồ sơ workspace',
  'Complete onboarding profile so roadmap, AI quiz, and mock-test flows can run correctly.': 'Vui lòng hoàn tất hồ sơ ban đầu để lộ trình, quiz AI và thi thử hoạt động chính xác.',
  'Source deleted': 'Đã xóa tài liệu',
  'Failed to delete source': 'Không thể xóa tài liệu',
  'Upload started, processing in background': 'Đã bắt đầu tải lên, đang xử lý nền',
  'Failed to upload material': 'Không thể tải lên tài liệu',
  'AI chat coming soon': 'Tính năng AI chat sẽ sớm ra mắt',
  'Uploading material...': 'Đang tải tài liệu...',
  'Missing workspace id': 'Thiếu workspace id',
  'Missing workspaceId': 'Thiếu workspaceId',
  'Please enter quiz title': 'Vui lòng nhập tiêu đề quiz',
  'Failed to load AI config metadata': 'Không thể tải metadata cấu hình AI',
  'AI quiz is being generated': 'Quiz AI đang được tạo',
  'Failed to generate quiz': 'Không thể tạo quiz',
  'Loading AI metadata...': 'Đang tải metadata AI...',
  'No materials available. Quiz can still be generated from prompt.': 'Chưa có tài liệu. Vẫn có thể tạo quiz từ prompt.',
  'Please choose one material': 'Vui lòng chọn một tài liệu',
  'Type percentages must sum to 100': 'Tổng phần trăm các loại phải bằng 100',
  'AI flashcard generation started': 'Đã bắt đầu tạo flashcard AI',
  'Failed to generate flashcards': 'Không thể tạo flashcard',
  'Failed to load quizzes': 'Không thể tải danh sách quiz',
  'Failed to load profile': 'Không thể tải hồ sơ',
  'Failed to update profile': 'Không thể cập nhật hồ sơ',
  'Avatar updated!': 'Đã cập nhật ảnh đại diện!',
  'Failed to upload avatar': 'Không thể tải ảnh đại diện',
  'Failed to pick image': 'Không thể chọn ảnh',
  'Name cannot be empty': 'Tên không được để trống',
  'Profile updated!': 'Đã cập nhật hồ sơ!',
  'Failed to load plan details': 'Không thể tải chi tiết gói',
  'Plan is unavailable': 'Gói hiện không khả dụng',
  'Please select a group first': 'Vui lòng chọn nhóm trước',
  'Payment URL was not returned': 'Không nhận được URL thanh toán',
  'Failed to create payment': 'Không thể tạo thanh toán',
  'Pre-learning generation started': 'Đã bắt đầu tạo quiz trước học',
  'Failed to generate pre-learning': 'Không thể tạo quiz trước học',
  'Knowledge quiz generation started': 'Đã bắt đầu tạo quiz kiến thức',
  'Failed to generate knowledge quiz': 'Không thể tạo quiz kiến thức',
  'Roadmap phase generation started': 'Đã bắt đầu tạo các giai đoạn lộ trình',
  'Failed to generate roadmap phases': 'Không thể tạo các giai đoạn lộ trình',
  'Failed to generate phase content': 'Không thể tạo nội dung giai đoạn',
  'AI flashcard creation is workspace-only currently': 'Tạo flashcard AI hiện chỉ hỗ trợ trong workspace cá nhân',
  'Use existing quizzes from this group for now': 'Hiện tại hãy dùng các quiz sẵn có trong nhóm này',
};

const PLAN_FEATURE_LABEL: Record<string, string> = {
  ADVANCE_QUIZ_CONFIG: 'Cấu hình quiz nâng cao',
  CREATE_ROADMAP: 'Tạo lộ trình học tập',
  AI_COMPANION_MODE: 'Chế độ AI đồng hành',
  WORKSPACE_ANALYTICS: 'Phân tích workspace',
  AI_SUMMARY_AND_TEXT_READING: 'AI tóm tắt & đọc văn bản',
  AI_QUIZ_ASSESSMENT_AND_RECOMMENDATION: 'AI đánh giá & gợi ý quiz',
};

export function getPlanFeatureLabel(feature?: string): string {
  if (!feature) return '';
  return PLAN_FEATURE_LABEL[String(feature).toUpperCase()] || feature;
}

export function localizeUiText(text?: string): string {
  if (!text) {
    return '';
  }

  const direct = UI_TEXT_MAP[text];
  if (direct) {
    return direct;
  }

  const compact = text.replace(/\s+/g, ' ').trim();
  return UI_TEXT_MAP[compact] || text;
}
